In [1]:
text = "hello world"
print(text.upper())

HELLO WORLD


In [2]:
import numpy as np
arr = np.array(['hello', 'world'])
print(np.char.upper(arr))

['HELLO' 'WORLD']


In [3]:
text = "hello world"
print(text.capitalize())  # Hello world
print(text.title())       # Hello World
print(text.swapcase())    # HELLO WORLD

Hello world
Hello World
HELLO WORLD


In [4]:
text = "   hello world   "
print(text.strip()) 

hello world


In [5]:
text = "banana apple banana"
print(text.find("banana"))     # 0
print(text.rfind("banana"))    # 13
print(text.index("apple"))     # 7

0
13
7


In [6]:
text = "banana apple banana"
print(text.count("banana"))          # 2
print(text.replace("banana", "mango"))

2
mango apple mango


In [7]:
print("hello".isalpha())   # True
print("123".isdigit())     # True
print("abc123".isalnum())  # True
print("   ".isspace())     # True

True
True
True
True


In [8]:
arr = np.array(['hello', 'world'])
print(np.char.upper(arr))  
print(np.char.lower(arr))  

['HELLO' 'WORLD']
['hello' 'world']


In [9]:
arr = np.array(['apple pie', 'banana pie'])
print(np.char.replace(arr, 'pie', 'juice'))

['apple juice' 'banana juice']


In [ ]:
arr = np.array(['hi', 'hello'])
print(np.char.center(arr, 10, fillchar='-'))

print(np.char.ljust(arr, 10, fillchar='*'))

['----hi----' '--hello---']
['hi********' 'hello*****']


In [11]:
arr = np.array(['  cat  ', '  dog  '])
print(np.char.strip(arr)) 

['cat' 'dog']


In [2]:
import numpy as np

arr = np.random.randint(1, 101, size=(3, 4, 5))
print("Original array:\n", arr)

mean_val = arr.mean()
print(mean_val)
arr[arr > mean_val] = 0
print("\nModified array (elements > mean set to 0):\n", arr)

sum_axis1 = arr.sum(axis=1)
print("\nSum along axis=1:\n", sum_axis1)

extracted = arr[:, :, [0, -1]]
print("\nExtracted first and last columns:\n", extracted)

Original array:
 [[[ 29  63  99  34  77]
  [ 37  54  81 100  10]
  [ 91  48  21  44  52]
  [ 50  80  63  79  76]]

 [[ 26  58  86 100   7]
  [ 55  81  39  69  42]
  [ 83  46   3  17  94]
  [ 76  65  88  81  72]]

 [[ 59  15  10  62  70]
  [ 37   1  88  51  71]
  [ 98  67  26  34  44]
  [ 27  84  40  87  41]]]
56.46666666666667

Modified array (elements > mean set to 0):
 [[[29  0  0 34  0]
  [37 54  0  0 10]
  [ 0 48 21 44 52]
  [50  0  0  0  0]]

 [[26  0  0  0  7]
  [55  0 39  0 42]
  [ 0 46  3 17  0]
  [ 0  0  0  0  0]]

 [[ 0 15 10  0  0]
  [37  1  0 51  0]
  [ 0  0 26 34 44]
  [27  0 40  0 41]]]

Sum along axis=1:
 [[116 102  21  78  62]
 [ 81  46  42  17  49]
 [ 64  16  76  85  85]]

Extracted first and last columns:
 [[[29  0]
  [37 10]
  [ 0 52]
  [50  0]]

 [[26  7]
  [55 42]
  [ 0  0]
  [ 0  0]]

 [[ 0  0]
  [37  0]
  [ 0 44]
  [27 41]]]
