In [1]:
text = "hello world"
print(text.upper())

HELLO WORLD


In [2]:
import numpy as np
arr = np.array(['hello', 'world'])
print(np.char.upper(arr))

['HELLO' 'WORLD']


In [3]:
text = "hello world"
print(text.capitalize())  # Hello world
print(text.title())       # Hello World
print(text.swapcase())    # HELLO WORLD

Hello world
Hello World
HELLO WORLD


In [4]:
text = "   hello world   "
print(text.strip()) 

hello world


In [5]:
text = "banana apple banana"
print(text.find("banana"))     # 0
print(text.rfind("banana"))    # 13
print(text.index("apple"))     # 7

0
13
7


In [6]:
text = "banana apple banana"
print(text.count("banana"))          # 2
print(text.replace("banana", "mango"))

2
mango apple mango


In [7]:
print("hello".isalpha())   # True
print("123".isdigit())     # True
print("abc123".isalnum())  # True
print("   ".isspace())     # True

True
True
True
True


In [8]:
arr = np.array(['hello', 'world'])
print(np.char.upper(arr))  
print(np.char.lower(arr))  

['HELLO' 'WORLD']
['hello' 'world']


In [9]:
arr = np.array(['apple pie', 'banana pie'])
print(np.char.replace(arr, 'pie', 'juice'))

['apple juice' 'banana juice']


In [10]:
arr = np.array(['hi', 'hello'])
print(np.char.center(arr, 10, fillchar='-'))

print(np.char.ljust(arr, 10, fillchar='*'))

['----hi----' '--hello---']
['hi********' 'hello*****']


In [11]:
arr = np.array(['  cat  ', '  dog  '])
print(np.char.strip(arr)) 

['cat' 'dog']


In [12]:
import numpy as np

arr = np.random.randint(1, 101, size=(3, 4, 5))
print("Original array:\n", arr)

mean_val = arr.mean()
print(mean_val)
arr[arr > mean_val] = 0
print("\nModified array (elements > mean set to 0):\n", arr)

sum_axis1 = arr.sum(axis=1)
print("\nSum along axis=1:\n", sum_axis1)

extracted = arr[:, :, [0, -1]]
print("\nExtracted first and last columns:\n", extracted)

Original array:
 [[[ 34  35  24  18   7]
  [  4  30  41  76  68]
  [  1  69  94  35  50]
  [ 92  55  70  73  50]]

 [[  7  40 100  66  48]
  [ 14   8  66  19  31]
  [ 24  73  98  36  99]
  [ 30   5  41  67   3]]

 [[ 20  83  48  25  39]
  [ 55  29  98  61  68]
  [ 54  25  60  18   2]
  [ 75  68  48  10  28]]]
45.25

Modified array (elements > mean set to 0):
 [[[34 35 24 18  7]
  [ 4 30 41  0  0]
  [ 1  0  0 35  0]
  [ 0  0  0  0  0]]

 [[ 7 40  0  0  0]
  [14  8  0 19 31]
  [24  0  0 36  0]
  [30  5 41  0  3]]

 [[20  0  0 25 39]
  [ 0 29  0  0  0]
  [ 0 25  0 18  2]
  [ 0  0  0 10 28]]]

Sum along axis=1:
 [[39 65 65 53  7]
 [75 53 41 55 34]
 [20 54  0 53 69]]

Extracted first and last columns:
 [[[34  7]
  [ 4  0]
  [ 1  0]
  [ 0  0]]

 [[ 7  0]
  [14 31]
  [24  0]
  [30  3]]

 [[20 39]
  [ 0  0]
  [ 0  2]
  [ 0 28]]]
