In [1]:
# Create a NumPy array of numbers from 10 to 50.

# Generate a 3×3 identity matrix.

# Create a NumPy array of 10 random integers between 1 and 100.

# Find the maximum and minimum of an array.

# Reshape a 1D array of 12 elements into a 3×4 matrix.

# Create an array of all even numbers between 50 and 100.

# Given an array [1,2,3,4,5], compute the square of each element.

# Create a 5×5 array of random numbers and find its mean.

# Find the index of the maximum element in [10, 20, 50, 40, 30].

# Create two arrays and perform element-wise addition, subtraction, multiplication, and division.


In [2]:
# Create a NumPy array of numbers from 10 to 50.

import numpy as np

arr1 = np.arange(10, 51)
print("Array 10 to 50:\n", arr1)

Array 10 to 50:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [3]:
# Generate a 3×3 identity matrix.
identity = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity)


3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# Create a NumPy array of 10 random integers between 1 and 100.
rand_ints = np.random.randint(1, 101, 10)
print("\n10 Random Integers (1-100):\n", rand_ints)


10 Random Integers (1-100):
 [34  8 70 14 88 95 26 39 13 96]


In [5]:
# Find the maximum and minimum of an array.
sample_arr = np.array([5, 12, 7, 30, 1, 18])
print("\nMax:", np.max(sample_arr))
print("Min:", np.min(sample_arr))


Max: 30
Min: 1


In [6]:
# Reshape a 1D array of 12 elements into a 3×4 matrix.
arr2 = np.arange(1, 13).reshape(3, 4)
print("\n3x4 Matrix:\n", arr2)


3x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
# Create an array of all even numbers between 50 and 100.
even_arr = np.arange(50, 101)   # or just use --> even_arr = np.arange(50, 101,2)
even_arr = even_arr[even_arr  %2 == 0]
print("\nEven numbers 50–100:\n", even_arr)


Even numbers 50–100:
 [ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100]


In [8]:
# Given an array [1,2,3,4,5], compute the square of each element.
arr3 = np.array([1, 2, 3, 4, 5])
print("\nSquares:\n", arr3 ** 2)


Squares:
 [ 1  4  9 16 25]


In [9]:
# Create a 5×5 array of random numbers and find its mean.
rand_arr = np.random.rand(5, 5)
print("\n5x5 Random Array:\n", rand_arr)
print("Mean:", np.mean(rand_arr))


5x5 Random Array:
 [[0.28046786 0.34940767 0.55061687 0.13589678 0.6883672 ]
 [0.19597345 0.98685882 0.61614776 0.00809571 0.16821075]
 [0.00661291 0.77779049 0.43069116 0.89302286 0.9747596 ]
 [0.10543137 0.64643037 0.95242579 0.6861027  0.04877337]
 [0.30872829 0.4204019  0.93434426 0.58029123 0.40534251]]
Mean: 0.4860476668168605


In [10]:
# Find the index of the maximum element in [10, 20, 50, 40, 30].
arr4 = np.array([10, 20, 50, 40, 30])
print("\nIndex of max element:", np.argmax(arr4))


Index of max element: 2


In [11]:
# Create two arrays and perform element-wise addition, subtraction, multiplication, and division.
a = np.array([10, 20, 30])
b = np.array([2, 4, 6])
print("\nElement-wise Addition:", a + b)
print("Element-wise Subtraction:", a - b)
print("Element-wise Multiplication:", a * b)
print("Element-wise Division:", a / b)


Element-wise Addition: [12 24 36]
Element-wise Subtraction: [ 8 16 24]
Element-wise Multiplication: [ 20  80 180]
Element-wise Division: [5. 5. 5.]
