In [2]:
import numpy as np 
array = np.array([1,2,3,4,5,6])
boolean = array >3
print(array)
print(boolean)

[1 2 3 4 5 6]
[False False False  True  True  True]


In [3]:
nm = np.array([1,2,3,4,5,6,7,8])
nm_copy = nm.copy()
print(nm_copy)

result = nm_copy[nm % 2 == 0]
print(result)

[1 2 3 4 5 6 7 8]
[2 4 6 8]


In [4]:
nm = np.array([1,2,3,4,5,6,7,8])
nm_copy = nm.copy()
print(nm_copy)

nm_copy[nm % 2 == 0] = True
print(nm_copy)

[1 2 3 4 5 6 7 8]
[1 1 3 1 5 1 7 1]


In [5]:
l1 = [1,2]
l2 = [3,4]
print(l1+l2)

[1, 2, 3, 4]


In [6]:
a1 = np.array([1,2]) #homogenous shape
a2 = np.array([3,4])
print(a1+a2)

[4 6]


In [7]:
#fancy indexing
array = np.array([1,2,3,4,5,6,7,8,9])
select_elements = array[[0,1,3,4]]
print(select_elements)

[1 2 4 5]


In [8]:
#array slicing
import numpy as np
nm = np.array([2,4,6,8,10,12,14])
sliced_numbers = nm[0:7:2]
print(sliced_numbers)

[ 2  6 10 14]


In [9]:
import numpy as np
nm = np.array([2,4,6,8,10,12,14])
sliced_numbers = nm[7:-8:-2]
print(sliced_numbers)

[14 10  6  2]


In [10]:
#array attributes
numbers = np.array([1,2,3,4,5,6,7,8])
print(numbers.ndim)
print(numbers.shape)
print(numbers.size)
print(numbers.dtype)

1
(8,)
8
int64


In [11]:
#2d array
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
#create a 2d array with 4 rows and 3 columns
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
#3d array
arr = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,20,30],
        [40,50,60],
        [70,80,90]
    ],
    [
        [15,25,35],
        [45,55,65],
        [75,85,95]
    ]
])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]

 [[15 25 35]
  [45 55 65]
  [75 85 95]]]


In [14]:
np_array = np.empty((4,3,2))
print(np_array)
print(np_array.ndim)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
3


In [15]:
np_array = np.zeros((4,3,2))
print(np_array)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [16]:
#.reshape 
arr1 = np.arange(1,65).reshape(4,4,4)
print(arr1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]


In [17]:
#np.reshape, order 1d to 2d and 3d
arr1 = np.arange(1,28)
print(arr1)
arr2 = arr1.reshape(3,9)
print(arr2)
arr3 = arr2.reshape(3,3,3)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [18]:
#3d array slicing
arr1 = np.arange(1,65).reshape(4,4,4)
print(arr1)
result = arr1[1,2,3] #block, row, column
print(result)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]
28


In [19]:
arr1 = np.arange(1,65).reshape(4,4,4)
result = arr1[:,2,:] # every block second index row each column
print(result)

[[ 9 10 11 12]
 [25 26 27 28]
 [41 42 43 44]
 [57 58 59 60]]


In [20]:
arr1 = np.arange(1,65).reshape(4,4,4)
result = arr1[:,:,2] # every block every row 2 index column
print(result)

[[ 3  7 11 15]
 [19 23 27 31]
 [35 39 43 47]
 [51 55 59 63]]


In [21]:
arr1 = np.arange(1,65).reshape(4,4,4)
result = arr1[2,:,:] # 2 index block every row every column; arr1[2] lekhda ni pugxa
print(result)

[[33 34 35 36]
 [37 38 39 40]
 [41 42 43 44]
 [45 46 47 48]]


In [22]:
#1d operation
import numpy as np

a = np.array([34,65,13,56,78,35,27,84,35,43,96,46])
print(a + 1)
print(a / 2)
print(a ** 2)
print(np.sqrt(a))
print(np.log(a))
print(np.exp(a))

[35 66 14 57 79 36 28 85 36 44 97 47]
[17.  32.5  6.5 28.  39.  17.5 13.5 42.  17.5 21.5 48.  23. ]
[1156 4225  169 3136 6084 1225  729 7056 1225 1849 9216 2116]
[5.83095189 8.06225775 3.60555128 7.48331477 8.83176087 5.91607978
 5.19615242 9.16515139 5.91607978 6.55743852 9.79795897 6.78232998]
[3.52636052 4.17438727 2.56494936 4.02535169 4.35670883 3.55534806
 3.29583687 4.4308168  3.55534806 3.76120012 4.56434819 3.8286414 ]
[5.83461743e+14 1.69488924e+28 4.42413392e+05 2.09165950e+24
 7.49841700e+33 1.58601345e+15 5.32048241e+11 3.02507732e+36
 1.58601345e+15 4.72783947e+18 4.92345829e+41 9.49611942e+19]


In [23]:
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.percentile(a,75))

612
13
96
51.0
44.5
24.10739858770885
581.1666666666666
68.25


In [24]:
print(a>50)
print(a[a>50])
print(np.where(a>50))

[False  True False  True  True False False  True False False  True False]
[65 56 78 84 96]
(array([ 1,  3,  4,  7, 10]),)


In [25]:
a = np.array([34,65,13,56,78,35,27,84,35,43,96,46])
a[0] = 10             # Change value
a = np.append(a, 6)   # Add element
a = np.insert(a, 1, 99) # Insert at index
a = np.delete(a, 2)    #dellete element
print(a)

[10 99 13 56 78 35 27 84 35 43 96 46  6]


In [26]:
print(np.sort(a))

[ 6 10 13 27 35 35 43 46 56 78 84 96 99]
