In [3]:
!pip install numpy

In [4]:
import numpy as np
list = {"string":2, 3:4}
array = np.array(list)
print(type(array))
print(array)

<class 'numpy.ndarray'>
{'string': 2, 3: 4}


In [5]:
line = np.linspace(0,10,10)
print(line)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [6]:
arr1 = np.linspace(1,10,6,endpoint = False)
print(arr1)

[1.  2.5 4.  5.5 7.  8.5]


In [7]:
random_number = np.random.randint(1,100)
print(random_number)
print(np.random.randint(1,51,10))

14
[33 31  1 32 40 12  3  2 29 23]


In [8]:
import numpy as np 
arr = np.array([10,20,30,40,50,60])
a = arr[arr>20]
a

array([30, 40, 50, 60])

In [9]:
arr = np.array([10,20,31,45,37,68,23])
e = arr[arr % 2 == 0]
e

array([10, 20, 68])

In [10]:
text = "hello world"
print(text.upper())

HELLO WORLD


In [11]:
import numpy as np
arr = np.array(['hello', 'world'])
print(np.char.upper(arr))

['HELLO' 'WORLD']


In [12]:
text = "hello world"
print(text.capitalize())  # Hello world
print(text.title())       # Hello World
print(text.swapcase())    # HELLO WORLD

Hello world
Hello World
HELLO WORLD


In [13]:
text = "   hello world   "
print(text.strip())   # "hello world"

hello world


In [14]:
text = "banana apple banana"
print(text.find("banana"))     # 0
print(text.rfind("banana"))    # 13
print(text.index("apple"))     # 7

0
13
7


In [15]:
text = "banana apple banana"
print(text.count("banana"))          # 2
print(text.replace("banana", "mango"))  # mango apple mango

2
mango apple mango


In [16]:
print("hello".isalpha())   
print("123".isdigit())     
print("abc123".isalnum())  
print("   ".isspace())     

True
True
True
True


In [17]:
!pip install scipy

   ---------------------------------------- 0.0/41.3 MB ? eta -:--:--
   - -------------------------------------- 1.3/41.3 MB 11.2 MB/s eta 0:00:04
   --- ------------------------------------ 3.9/41.3 MB 18.1 MB/s eta 0:00:03
   ---------- ----------------------------- 10.7/41.3 MB 20.3 MB/s eta 0:00:02
   --------------- ------------------------ 15.7/41.3 MB 21.5 MB/s eta 0:00:02
   ------------------- -------------------- 20.4/41.3 MB 22.3 MB/s eta 0:00:01
   ------------------------ --------------- 25.4/41.3 MB 22.4 MB/s eta 0:00:01
   ----------------------------- ---------- 30.4/41.3 MB 22.7 MB/s eta 0:00:01
   ---------------------------------- ----- 35.4/41.3 MB 22.9 MB/s eta 0:00:01
   ---------------------------------------  40.4/41.3 MB 23.1 MB/s eta 0:00:01
   ---------------------------------------- 41.3/41.3 MB 22.2 MB/s  0:00:01


In [18]:
from scipy import stats
import numpy as np

marks = np.array([82,85,83,89,86,85,84,86,89,86,86,86,86,81,81,81,81,81,81])
# same choti duita number repeate bhako xa bhane sano number print hunxa
mode = stats.mode(marks)
print(mode)
print(mode.mode, mode.count)

ModeResult(mode=np.int64(81), count=np.int64(6))
81 6


In [19]:
#matrix operation
#addition
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])
print(a+b)

[[3 5]
 [7 9]]


In [20]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])
print(a*b) # each element got multiplied

[[ 2  6]
 [12 20]]


In [21]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])
print(np.matmul(a,b))

[[10 13]
 [22 29]]


In [22]:
#matrix:
#matrix multiplication is possible through this or matmul
a = np.matrix([[1,2],[3,4]])
b = np.matrix([[2,3],[4,5]])
print(a*b)
print(a**2) #it is a*a but if not done in matrix then it would just power each element by 2


[[10 13]
 [22 29]]
[[ 7 10]
 [15 22]]


In [23]:
#transpose: row and column swap
r = np.transpose(a) #for normal array
print(r)
print(np.transpose(a))
print(a.T) # for matrix

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [24]:
e = np.eye(N=3,M=3,k=1) #k: 0 = main diagonal,1 = above main,-1 = below main so on
print(e)
m2 = np.identity(4)
print(m2)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
#You are given a numpy 2d array of shape(4,5) replace the element in the array that are greater than  the means of the array with 0 and leave the rest unchanged.
import numpy as np

arr = np.random.randint(1,100,size=(4,5))

mean_val = arr.mean()
print("Mean:", mean_val)

arr[arr > mean_val] = 0

print("Modified array:\n", arr)


Mean: 48.0
Modified array:
 [[ 0  0 33  0 42]
 [18  0  0  0  0]
 [26 20  4  0  0]
 [27 37  0  0  0]]


In [26]:
ar1 = np.array([[-3,1,5,-3,-5],[2,-5,3,-5,-6]])
print(np.where(ar1<0,0,1))  #negative replaced by 0 and positive by 1

[[0 1 1 0 0]
 [1 0 1 0 0]]


In [27]:
arangle = np.random.randint(1,11,5)
print(arangle)
print(np.sin(arangle))
print(np.cos(arangle))
print(np.tan(arangle))

[9 8 1 4 9]
[ 0.41211849  0.98935825  0.84147098 -0.7568025   0.41211849]
[-0.91113026 -0.14550003  0.54030231 -0.65364362 -0.91113026]
[-0.45231566 -6.79971146  1.55740772  1.15782128 -0.45231566]


In [28]:
X = np.array([1,2,3])
print(np.log(X))
print(np.exp(X))

[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]


In [29]:
a = np.round(np.random.rand(10),2)  #round of to two decimal place
print(a)

[0.99 0.61 0.54 0.32 0.78 0.67 0.9  0.65 0.25 0.23]
