In [1]:
#numpy broadcasting perform arithemetic operation on array with different shapes and sizes.
#scaler broadcasting
import numpy as np

array = np.array([[1,2],[3,4]])
scaler = 15         # broadcasted the constant variable
result = array + scaler
result

array([[16, 17],
       [18, 19]])

In [2]:
a = [[1,2],[4,5]]
scaler = 10
result = []
for i in a:
    new_row = []
    for item in i:
        new_row.append(item+scaler)
    result.append(new_row)
for i in result:
    print(i)

[11, 12]
[14, 15]


In [3]:
#hybrid broadcasting
A = np.array([[1,2,3],[4,5,6]])
B = np.array([10,20,30])
C = A + B
print(C)

[[11 22 33]
 [14 25 36]]


In [4]:
q1 = np.random.randint(1,101,size=(2,3,4))
print(q1)

[[[53 65 91 72]
  [83 51  9 10]
  [10 83 76 47]]

 [[92 65 69 92]
  [76 89 29 87]
  [40 43  5 84]]]


In [5]:
# if > 50 replace with -1
a = np.random.randint(1,101,size=(2,3,4))
a[a>50] = -1
print(a)

[[[-1 47 24 14]
  [-1 -1 24 -1]
  [19 -1 48 -1]]

 [[ 8  8 12  9]
  [38 -1 -1 -1]
  [ 4 -1 34 -1]]]


In [6]:
import numpy as np
ar1 = np.arange(1,11,1)

e = ar1[ar1%2==0]
print(e)

[ 2  4  6  8 10]


In [7]:
import numpy as np
marks = np.array([5,35,7,4,1,90])
# if std is small then  dataset is closer to its mean
sd = np.std(marks)
print(sd)

31.76825809235096


In [8]:
array1 = np.arange(1,101,0.25)
print(array1)
result1 = np.percentile(array1,50)
print(result1)
print(np.median(array1))

[  1.     1.25   1.5    1.75   2.     2.25   2.5    2.75   3.     3.25
   3.5    3.75   4.     4.25   4.5    4.75   5.     5.25   5.5    5.75
   6.     6.25   6.5    6.75   7.     7.25   7.5    7.75   8.     8.25
   8.5    8.75   9.     9.25   9.5    9.75  10.    10.25  10.5   10.75
  11.    11.25  11.5   11.75  12.    12.25  12.5   12.75  13.    13.25
  13.5   13.75  14.    14.25  14.5   14.75  15.    15.25  15.5   15.75
  16.    16.25  16.5   16.75  17.    17.25  17.5   17.75  18.    18.25
  18.5   18.75  19.    19.25  19.5   19.75  20.    20.25  20.5   20.75
  21.    21.25  21.5   21.75  22.    22.25  22.5   22.75  23.    23.25
  23.5   23.75  24.    24.25  24.5   24.75  25.    25.25  25.5   25.75
  26.    26.25  26.5   26.75  27.    27.25  27.5   27.75  28.    28.25
  28.5   28.75  29.    29.25  29.5   29.75  30.    30.25  30.5   30.75
  31.    31.25  31.5   31.75  32.    32.25  32.5   32.75  33.    33.25
  33.5   33.75  34.    34.25  34.5   34.75  35.    35.25  35.5   35.75
  36. 

In [9]:
print(np.percentile(array1,25))
print(np.percentile(array1,75))
print(np.min(array1))
print(np.max(array1))

25.9375
75.8125
1.0
100.75


In [10]:
ar = np.full(shape = (2,3,4), fill_value =8)
print(ar)

[[[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]

 [[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]]


In [11]:
#flatten
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr.flatten())

[1 2 3 4]


In [12]:
#2d to 3D
import numpy as np

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

arr3d = arr2d.reshape(2, 3, 1)   # turn (2,3) into (2,3,1)
print(arr3d)  # (2, 3, 1)

arr3d = arr2d.reshape(1, 3, 2)   # turn (2,3) into (1,3,2)
print(arr3d)  # (1, 3, 2)

arr3d = np.expand_dims(arr2d, axis=0)
print(arr3d)   # .reshape(1,2,3)

arr3d = np.expand_dims(arr2d, axis=-1)
print(arr3d)   #.reshape(2,3,1)

arr3d = np.expand_dims(arr2d, axis=1)
print(arr3d)   #.reshape(2,1,3)

#shorthand for expand_dims
arr3d = arr2d[:,np.newaxis,:]
print(arr3d)   #.reshape(2,1,3)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[[[1 2]
  [3 4]
  [5 6]]]
[[[1 2 3]
  [4 5 6]]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[[[1 2 3]]

 [[4 5 6]]]
[[[1 2 3]]

 [[4 5 6]]]


In [13]:
import numpy as np
a1 = np.array([1,2,3,4,5,6,7,8])
r = np.reshape(a1, (2,4),order='F') #by default C
print(r)

[[1 3 5 7]
 [2 4 6 8]]


In [14]:
#array to matrix
import numpy as np

arr = np.array([[1, 2], [3, 4]])
print(type(arr))   # <class 'numpy.ndarray'>

mat = np.asmatrix(arr)
print(type(mat))    # <class 'numpy.matrix'>

back_to_array = np.asarray(mat)
print(type(back_to_array))  # <class 'numpy.ndarray'>

<class 'numpy.ndarray'>
<class 'numpy.matrix'>
<class 'numpy.ndarray'>


In [15]:
import numpy as np
ar1 = np.array([[2,3],[6,8]])
ar2 = np.array([[7,4],[5,9]])

res = np.dot(ar1,ar2)
#if array is 2d it does matrix multiplication
#if array is 1d, multiplies each element of array and sums it
print(res)
print(np.matmul(ar1,ar2))
print(ar1 @ ar2)

[[29 35]
 [82 96]]
[[29 35]
 [82 96]]
[[29 35]
 [82 96]]


In [16]:
ar1 = np.array([1,2,3])
ar2 = np.array([5,6,7])
print(np.dot(ar1,ar2))
print(ar1 @ ar2)

38
38


In [17]:
#stack
import numpy as np

ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])

res = np.stack((ar1,ar2),axis = 0)
print(res)
res = np.stack((ar1,ar2),axis = 1)
print(res)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [18]:
ar1 = np.array([[2,3,4],[6,8,7],[6,3,9]])
print(ar1)
col = np.sum(ar1, axis = 1) #2+3+4
print(col)
row = np.sum(ar1, axis = 0) #2+6+6
print(row)


[[2 3 4]
 [6 8 7]
 [6 3 9]]
[ 9 21 18]
[14 14 20]


In [19]:
ar1 = np.array([[2,3,4],[6,8,7],[6,3,9]])
print(ar1)
col = np.mean(ar1, axis = 1) #(2+3+4)/3
print(col)
row = np.mean(ar1, axis = 0) #(2+6+6)/3
print(row)

[[2 3 4]
 [6 8 7]
 [6 3 9]]
[3. 7. 6.]
[4.66666667 4.66666667 6.66666667]


In [20]:
import numpy as np

n = 8  # size (n x n)
board = (np.indices((n, n)))
print(board)
board = (np.indices((n, n)).sum(axis=0))
print(board)
board = (np.indices((n, n)).sum(axis=0) % 2)
print(board)

[[[0 0 0 0 0 0 0 0]
  [1 1 1 1 1 1 1 1]
  [2 2 2 2 2 2 2 2]
  [3 3 3 3 3 3 3 3]
  [4 4 4 4 4 4 4 4]
  [5 5 5 5 5 5 5 5]
  [6 6 6 6 6 6 6 6]
  [7 7 7 7 7 7 7 7]]

 [[0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]]]
[[ 0  1  2  3  4  5  6  7]
 [ 1  2  3  4  5  6  7  8]
 [ 2  3  4  5  6  7  8  9]
 [ 3  4  5  6  7  8  9 10]
 [ 4  5  6  7  8  9 10 11]
 [ 5  6  7  8  9 10 11 12]
 [ 6  7  8  9 10 11 12 13]
 [ 7  8  9 10 11 12 13 14]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
