In [1]:
!pip install numpy

In [2]:
import numpy as np
list = {"string":2, 3:4}
array = np.array(list)
print(type(array))
print(array)

<class 'numpy.ndarray'>
{'string': 2, 3: 4}


In [5]:
line = np.linspace(0,10,10)
print(line)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [10]:
arr1 = np.linspace(1,10,6,endpoint = False)
print(arr1)

[1.  2.5 4.  5.5 7.  8.5]


In [11]:
random_number = np.random.randint(1,100)
print(random_number)
print(np.random.randint(1,51,10))

24
[ 8 45 26 35 18 37  2 25  7 28]


In [12]:
import numpy as np 
arr = np.array([10,20,30,40,50,60])
a = arr[arr>20]
a

array([30, 40, 50, 60])

In [13]:
arr = np.array([10,20,31,45,37,68,23])
e = arr[arr % 2 == 0]
e

array([10, 20, 68])

In [1]:
text = "hello world"
print(text.upper())

HELLO WORLD


In [2]:
import numpy as np
arr = np.array(['hello', 'world'])
print(np.char.upper(arr))

['HELLO' 'WORLD']


In [3]:
text = "hello world"
print(text.capitalize())  # Hello world
print(text.title())       # Hello World
print(text.swapcase())    # HELLO WORLD

Hello world
Hello World
HELLO WORLD


In [4]:
text = "   hello world   "
print(text.strip())   # "hello world"

hello world


In [5]:
text = "banana apple banana"
print(text.find("banana"))     # 0
print(text.rfind("banana"))    # 13
print(text.index("apple"))     # 7

0
13
7


In [6]:
text = "banana apple banana"
print(text.count("banana"))          # 2
print(text.replace("banana", "mango"))  # mango apple mango

2
mango apple mango


In [7]:
print("hello".isalpha())   
print("123".isdigit())     
print("abc123".isalnum())  
print("   ".isspace())     

True
True
True
True


In [1]:
!pip install scipy

   ---------------------------------------- 0.0/38.6 MB ? eta -:--:--
   - -------------------------------------- 1.6/38.6 MB 12.0 MB/s eta 0:00:04
   --- ------------------------------------ 3.7/38.6 MB 15.6 MB/s eta 0:00:03
   --------- ------------------------------ 9.2/38.6 MB 16.8 MB/s eta 0:00:02
   -------------- ------------------------- 13.9/38.6 MB 18.6 MB/s eta 0:00:02
   ------------------- -------------------- 18.9/38.6 MB 19.9 MB/s eta 0:00:01
   ------------------------ --------------- 23.9/38.6 MB 20.4 MB/s eta 0:00:01
   ----------------------------- ---------- 28.6/38.6 MB 20.6 MB/s eta 0:00:01
   ---------------------------------- ----- 33.3/38.6 MB 20.7 MB/s eta 0:00:01
   -------------------------------------- - 37.0/38.6 MB 20.6 MB/s eta 0:00:01
   ---------------------------------------- 38.6/38.6 MB 20.0 MB/s eta 0:00:00


In [6]:
from scipy import stats
import numpy as np

marks = np.array([82,85,83,89,86,85,84,86,89,86,86,86,86,81,81,81,81,81,81])
# same choti duita number repeate bhako xa bhane sano number print hunxa
mode = stats.mode(marks)
print(mode)
print(mode.mode, mode.count)

ModeResult(mode=np.int64(81), count=np.int64(6))
81 6


In [3]:
#matrix operation
#addition
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])
print(a+b)

[[3 5]
 [7 9]]


In [4]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])
print(a*b) # each element got multiplied

[[ 2  6]
 [12 20]]


In [5]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])
print(np.matmul(a,b))

[[10 13]
 [22 29]]


In [7]:
#matrix:
#matrix multiplication is possible through this or matmul
a = np.matrix([[1,2],[3,4]])
b = np.matrix([[2,3],[4,5]])
print(a*b)
print(a**2) #it is a*a but if not done in matrix then it would just power each element by 2


[[10 13]
 [22 29]]
[[ 7 10]
 [15 22]]


In [11]:
#transpose: row and column swap
r = np.transpose(a) #for normal array
print(r)
print(np.transpose(a))
print(a.T) # for matrix

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [22]:
e = np.eye(N=3,M=3,k=1) #k: 0 = main diagonal,1 = above main,-1 = below main so on
print(e)
m2 = np.identity(4)
print(m2)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
#You are given a numpy 2d array of shape(4,5) replace the element in the array that are greater than  the means of the array with 0 and leave the rest unchanged.
import numpy as np

arr = np.random.randint(1,100,size=(4,5))

mean_val = arr.mean()
print("Mean:", mean_val)

arr[arr > mean_val] = 0

print("Modified array:\n", arr)


Mean: 49.1
Modified array:
 [[ 0 21  0 31  2]
 [ 0 30  0 10 49]
 [30 34  0  0  0]
 [21  0 22 41  0]]


In [6]:
ar1 = np.array([[-3,1,5,-3,-5],[2,-5,3,-5,-6]])
print(np.where(ar1<0,0,1))  #negative replaced by 0 and positive by 1

[[0 1 1 0 0]
 [1 0 1 0 0]]


In [8]:
arangle = np.random.randint(1,11,5)
print(arangle)
print(np.sin(arangle))
print(np.cos(arangle))
print(np.tan(arangle))

[ 5  5  1 10  9]
[-0.95892427 -0.95892427  0.84147098 -0.54402111  0.41211849]
[ 0.28366219  0.28366219  0.54030231 -0.83907153 -0.91113026]
[-3.38051501 -3.38051501  1.55740772  0.64836083 -0.45231566]


In [10]:
X = np.array([1,2,3])
print(np.log(X))
print(np.exp(X))

[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]


In [12]:
a = np.round(np.random.rand(10),2)  #round of to two decimal place
print(a)

[0.22 0.03 0.37 0.1  0.45 0.13 0.03 0.83 0.93 0.53]
